[project]
name = "wtftw_core"
version = "0.3.2"
authors = ["Simon Wollwage"]

[dependencies]
bitflags = "0.5.0"
serde_json = "1.0.16"
log = "*"
num = "*"
libc = "*"
dylib = "*"

[lib]
name = "wtftw_core"
path = "src/wtftw.rs"
crate-type = ["rlib"]
